version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g aws-cdk dotenv-cli esbuild --unsafe-perm --progress=false --silent
  pre_build:
    commands:
      - cd source/constructs
      - rm -rf node_modules/ package-lock.json
      - ls .
      - npm install
      - ls node_modules
  # build:
  #   commands:
  #     - npm run build # we don't need to build, deploy will build before deploying
  post_build:
    commands:
      - npm run deploy
